server:
  port: 8081

# Customize JVM options to prevent OutOfMemoryError
spring:
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 10
        allow-core-thread-timeout: true
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 10s